# Generated by Django 2.2.9 on 2020-02-26 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mod',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TexturePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texture_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Texture pack',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TexturePackVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc', models.FileField(max_length=1000, upload_to='', verbose_name='File')),
                ('texture_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contentdb.TexturePack')),
            ],
            options={
                'verbose_name': 'Texture pack version',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ModVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc', models.FileField(max_length=1000, upload_to='', verbose_name='File')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contentdb.Mod')),
            ],
            options={
                'verbose_name': 'Mod version',
                'ordering': ['date'],
            },
        ),
    ]
