# Generated by Django 2.2.9 on 2020-02-26 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contentdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='texturepack',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
