# Generated by Django 3.0.3 on 2020-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentdb', '0004_auto_20200309_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modversion',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='texturepackversion',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='modversion',
            unique_together={('mod', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='texturepackversion',
            unique_together={('texture_pack', 'name')},
        ),
    ]
