# Generated by Django 3.0.3 on 2020-03-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentdb', '0006_auto_20200326_0256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
