# Generated by Django 3.0.5 on 2020-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentdb', '0007_delete_newsarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineversion',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='modversion',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='texturepackversion',
            name='doc',
        ),
        migrations.AddField(
            model_name='engineversion',
            name='linux_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineversion',
            name='linux_zip',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Linux ZIP'),
        ),
        migrations.AddField(
            model_name='engineversion',
            name='macos_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineversion',
            name='macos_zip',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Linux ZIP'),
        ),
        migrations.AddField(
            model_name='engineversion',
            name='windows_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineversion',
            name='windows_zip',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Windows ZIP'),
        ),
        migrations.AddField(
            model_name='modversion',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modversion',
            name='file_zip',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='texturepackversion',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='texturepackversion',
            name='file_zip',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='engineversion',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='modversion',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='texturepackversion',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
