# Generated by Django 3.0.5 on 2020-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentdb', '0008_auto_20200507_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineversion',
            name='macos_zip',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='macOS ZIP'),
        ),
    ]
